"""Seed 3 realistic, fully-finalized example encounters into the
`encounters` table for the two bundled fictitious patients (Avery Kim,
Riley Thompson).

These are hand-authored (not generated by a live LLM call, to keep this
repo's setup free to run), but they are exactly the kind of output a real
run of `extract_structured_node` / `code_lookup_node` /
`generate_patient_summary_node` against the corresponding note in
`sample-data/notes/` would plausibly produce, and each carries a realistic
clinician decision (approve / correct / reject-style history) and trace.
They exist so the "Patient Encounter History / Example Analyses" page has
real, varied content before a visitor uploads or runs anything themselves.

Run with:
    python -m scripts.seed_examples

Requires `scripts/seed_patients.py` to have already run (the patients this
script attaches encounters to must already exist).
"""
from __future__ import annotations

from datetime import datetime, timedelta, timezone

from app.db.models import Encounter
from app.db.session import SessionLocal


def _iso(dt: datetime) -> str:
    return dt.isoformat()


def _trace(base: datetime, node: str, minutes: float, summary: str) -> dict:
    return {"node": node, "timestamp": _iso(base + timedelta(minutes=minutes)), "summary": summary}


def _seed_one(
    *,
    encounter_id: str,
    patient_id: str,
    original_filename: str,
    structured_note: dict,
    code_suggestions: list,
    accepted_codes: dict,
    patient_summary: str,
    human_decision: str,
    human_feedback: str,
    days_ago: float,
    review_delay_minutes: float,
) -> None:
    with SessionLocal() as db:
        if db.get(Encounter, encounter_id) is not None:
            print(f"[skip] encounter {encounter_id!r} already seeded")
            return

    t0 = datetime.now(timezone.utc) - timedelta(days=days_ago)

    if human_decision == "reject":
        final_status, status = "rejected", "rejected"
    else:
        final_status = "corrected_and_added" if human_decision == "correct" else "added_to_record"
        status = "completed"

    trace = [
        _trace(t0, "ingest", 0.0, f"Detected plain-text note; read {original_filename}."),
        _trace(t0, "extract_structured", 0.4, f"Extracted {len(structured_note.get('problem_list', []))} problem(s) and {len(structured_note.get('medications', []))} medication(s)."),
        _trace(t0, "code_lookup", 0.6, f"Looked up suggested ICD-10 codes for {len(code_suggestions)} problem(s) (for clinician confirmation)."),
        _trace(t0, "generate_patient_summary", 0.9, f"Generated a {len(patient_summary)}-character patient summary."),
        _trace(t0, "clinician_review", review_delay_minutes, f"Clinician decision={human_decision} | {human_feedback[:200]}"),
        _trace(t0, "finalize", review_delay_minutes + 0.1, f"Encounter finalized with status={final_status}."),
    ]
    state_snapshot = {
        "structured_note": structured_note,
        "code_suggestions": code_suggestions,
        "accepted_codes": accepted_codes,
        "patient_summary": patient_summary,
        "human_decision": human_decision,
        "human_feedback": human_feedback,
        "final_status": final_status,
        "status": status,
    }

    encounter = Encounter(
        id=encounter_id,
        patient_id=patient_id,
        original_filename=original_filename,
        status=status,
        final_status=final_status,
        structured_note=structured_note,
        code_suggestions=code_suggestions,
        accepted_codes=accepted_codes,
        patient_summary=patient_summary,
        trace=trace,
        state_snapshot=state_snapshot,
        error=None,
        created_at=t0,
        updated_at=t0 + timedelta(minutes=review_delay_minutes + 0.1),
    )
    with SessionLocal() as db:
        db.add(encounter)
        db.commit()
    print(f"[seeded] encounter {encounter_id!r} ({original_filename}, {final_status})")


def seed() -> None:
    # ---------------------------------------------------------------
    # Avery Kim -- simple outpatient visit, single problem, approved as-is.
    # ---------------------------------------------------------------
    pharyngitis_problem = (
        "Acute pharyngitis, likely streptococcal given exudate and tender "
        "adenopathy; rapid strep test positive."
    )
    _seed_one(
        encounter_id="seed-pharyngitis-avery-kim",
        patient_id="avery-kim",
        original_filename="outpatient_pharyngitis_avery_kim.txt",
        structured_note={
            "chief_complaint": "Sore throat and low-grade fever for 3 days.",
            "problem_list": [{"description": pharyngitis_problem}],
            "medications": [
                {
                    "name": "Amoxicillin",
                    "dosage": "500 mg",
                    "frequency": "by mouth twice daily for 10 days",
                    "notes": "New; for streptococcal pharyngitis",
                }
            ],
            "allergies": [],
            "follow_up_instructions": [
                "Return to clinic or seek urgent care if symptoms worsen, if difficulty "
                "breathing or swallowing develops, or if fever persists beyond 3 days on antibiotics.",
                "Complete the full 10-day course of amoxicillin even if feeling better.",
                "Follow up with this clinic in 2 weeks if symptoms have not fully resolved.",
            ],
            "referrals": [],
            "vitals": {
                "blood_pressure": "118/76",
                "heart_rate": "88",
                "temperature": "100.4 F",
                "respiratory_rate": "16",
                "oxygen_saturation": "98%",
                "weight": "",
                "height": "",
            },
        },
        code_suggestions=[
            {
                "problem": pharyngitis_problem,
                "suggestions": [
                    {"code": "J02.9", "description": "Acute pharyngitis unspecified", "score": 0.91},
                    {"code": "J06.9", "description": "Acute upper respiratory infection unspecified", "score": 0.62},
                ],
            }
        ],
        accepted_codes={pharyngitis_problem: "J02.9"},
        patient_summary=(
            "Your visit summary: You came in with a sore throat and a mild fever. Your rapid "
            "strep test was positive, so you were diagnosed with a strep throat infection (acute "
            "pharyngitis). You were started on amoxicillin, an antibiotic, to take twice a day for "
            "10 days -- please finish the entire course even if you start feeling better. Gargling "
            "with warm salt water and taking acetaminophen or ibuprofen can help with the pain and "
            "fever. Please return to the clinic or seek urgent care if your symptoms get worse, if "
            "you have trouble breathing or swallowing, or if your fever lasts more than 3 days after "
            "starting the antibiotic. This summary was reviewed and approved by your clinician."
        ),
        human_decision="approve",
        human_feedback="Correct diagnosis and coding; summary reads clearly for the patient.",
        days_ago=20,
        review_delay_minutes=18,
    )

    # ---------------------------------------------------------------
    # Avery Kim -- medication change, CORRECTED by the clinician (wording
    # clarified) before being added, demonstrating the "correct" decision.
    # ---------------------------------------------------------------
    htn_problem = (
        "Essential (primary) hypertension, well controlled, discontinuing lisinopril due to "
        "ACE-inhibitor-induced dry cough (not due to lack of efficacy)."
    )
    _seed_one(
        encounter_id="seed-htn-medchange-avery-kim",
        patient_id="avery-kim",
        original_filename="hypertension_med_change_avery_kim.txt",
        structured_note={
            "chief_complaint": "Follow-up for hypertension; new dry cough since starting blood pressure medication.",
            "problem_list": [{"description": htn_problem}],
            "medications": [
                {"name": "Losartan", "dosage": "50 mg", "frequency": "by mouth once daily", "notes": "New, replacing lisinopril"},
                {"name": "Lisinopril", "dosage": "10 mg", "frequency": "by mouth once daily", "notes": "Discontinued today"},
                {"name": "Atorvastatin", "dosage": "10 mg", "frequency": "by mouth at bedtime", "notes": "Continued, unchanged"},
            ],
            "allergies": ["No known drug allergies"],
            "follow_up_instructions": [
                "Recheck blood pressure and basic metabolic panel in 4 weeks.",
                "Call the clinic if cough does not improve within 4 weeks of stopping lisinopril, "
                "or sooner if swelling of the lips/tongue/face occurs.",
                "Continue low-sodium diet and current exercise routine.",
            ],
            "referrals": [],
            "vitals": {
                "blood_pressure": "126/80",
                "heart_rate": "74",
                "temperature": "98.2 F",
                "respiratory_rate": "14",
                "oxygen_saturation": "",
                "weight": "168 lb",
                "height": "",
            },
        },
        code_suggestions=[
            {
                "problem": htn_problem,
                "suggestions": [{"code": "I10", "description": "Essential (primary) hypertension", "score": 0.95}],
            }
        ],
        accepted_codes={htn_problem: "I10"},
        patient_summary=(
            "Your visit summary: You came in for a check on your blood pressure medication because "
            "you developed a dry cough after starting lisinopril. Your clinician believes the cough "
            "is caused by this type of blood pressure medicine (an ACE inhibitor). Your lisinopril "
            "has been stopped, and you've been started on a different blood pressure medicine called "
            "losartan instead, taken once daily. You'll continue your atorvastatin as before. Your "
            "blood pressure today was well controlled. The cough should improve over the next 1 to 4 "
            "weeks now that lisinopril has been stopped. Please recheck your blood pressure and have "
            "blood work done in 4 weeks, and call the clinic if the cough hasn't improved by then, or "
            "right away if you notice swelling of your lips, tongue, or face. This summary was "
            "reviewed and approved by your clinician."
        ),
        human_decision="correct",
        human_feedback=(
            "Clarified that lisinopril was stopped specifically due to the ACE-inhibitor cough, "
            "not lack of blood pressure control."
        ),
        days_ago=10,
        review_delay_minutes=9,
    )

    # ---------------------------------------------------------------
    # Riley Thompson -- complex multi-diagnosis discharge summary, approved
    # as-is, demonstrating a longer problem/medication list.
    # ---------------------------------------------------------------
    chf_problems = [
        "Acute on chronic systolic heart failure exacerbation, now improved",
        "Type 2 diabetes mellitus, suboptimally controlled during admission",
        "Essential hypertension, uncontrolled on admission, improved with medication adjustment",
        "Chronic kidney disease, stage 3, stable",
    ]
    chf_code_map = [
        ("I50.9", "Heart failure unspecified", 0.89),
        ("E11.65", "Type 2 diabetes mellitus with hyperglycemia", 0.84),
        ("I10", "Essential (primary) hypertension", 0.90),
        ("N18.30", "Chronic kidney disease stage 3 unspecified", 0.93),
    ]
    chf_code_suggestions = [
        {
            "problem": problem,
            "suggestions": (
                [{"code": code, "description": desc, "score": score}]
                if problem != chf_problems[1]
                else [
                    {"code": code, "description": desc, "score": score},
                    {"code": "E11.9", "description": "Type 2 diabetes mellitus without complications", "score": 0.70},
                ]
            ),
        }
        for problem, (code, desc, score) in zip(chf_problems, chf_code_map, strict=True)
    ]
    chf_accepted_codes = {problem: code for problem, (code, _, _) in zip(chf_problems, chf_code_map, strict=True)}
    _seed_one(
        encounter_id="seed-chf-discharge-riley-thompson",
        patient_id="riley-thompson",
        original_filename="discharge_chf_multidx_riley_thompson.txt",
        structured_note={
            "chief_complaint": "Shortness of breath and lower extremity swelling.",
            "problem_list": [{"description": p} for p in chf_problems],
            "medications": [
                {"name": "Furosemide", "dosage": "40 mg", "frequency": "by mouth once daily", "notes": "Increased from 20 mg prior to admission"},
                {"name": "Metformin", "dosage": "1000 mg", "frequency": "by mouth twice daily", "notes": "Unchanged"},
                {"name": "Empagliflozin", "dosage": "10 mg", "frequency": "by mouth once daily", "notes": "Newly added this admission"},
                {"name": "Losartan", "dosage": "100 mg", "frequency": "by mouth once daily", "notes": "Increased from 50 mg"},
                {"name": "Metoprolol succinate", "dosage": "50 mg", "frequency": "by mouth once daily", "notes": "Unchanged"},
                {"name": "Atorvastatin", "dosage": "40 mg", "frequency": "by mouth at bedtime", "notes": "Unchanged"},
            ],
            "allergies": ["Penicillin - rash"],
            "follow_up_instructions": [
                "Weigh yourself daily each morning; call the heart failure clinic if weight "
                "increases more than 3 pounds in 2 days.",
                "Follow a low-sodium (less than 2000 mg/day) diet.",
                "Follow-up with primary care (Cedar Hollow Family Health Clinic) within 7 days of discharge.",
                "Follow-up with Cardiology (Dr. Nadia Farouk) in 2 weeks.",
                "Recheck basic metabolic panel and kidney function 1 week after discharge given "
                "the diuretic dose increase.",
            ],
            "referrals": ["Referral placed to outpatient diabetes education program."],
            "vitals": {
                "blood_pressure": "",
                "heart_rate": "",
                "temperature": "",
                "respiratory_rate": "",
                "oxygen_saturation": "",
                "weight": "",
                "height": "",
            },
        },
        code_suggestions=chf_code_suggestions,
        accepted_codes=chf_accepted_codes,
        patient_summary=(
            "Your hospital stay summary: You were admitted because of shortness of breath and "
            "swelling in your legs, related to your heart failure. While in the hospital, you were "
            "given medication through an IV to help remove extra fluid, and your breathing improved. "
            "Your blood sugar and blood pressure were also adjusted during your stay. You're being "
            "discharged with a few things to manage: a heart failure flare-up (now improved), type 2 "
            "diabetes, high blood pressure, and stage 3 chronic kidney disease. Your water pill "
            "(furosemide) dose was increased, a new diabetes medication (empagliflozin) was added, "
            "and your blood pressure medication (losartan) dose was also increased. Please weigh "
            "yourself every morning and call the heart failure clinic if you gain more than 3 pounds "
            "in 2 days. Follow a low-salt diet, see your primary care doctor within 7 days, and see "
            "cardiology in 2 weeks. Blood work is needed in 1 week to check your kidneys after the "
            "medication changes. A referral was also placed for diabetes education classes. This "
            "summary was reviewed and approved by your clinician."
        ),
        human_decision="approve",
        human_feedback="Discharge summary accurate; codes match discharge diagnoses.",
        days_ago=6,
        review_delay_minutes=40,
    )

    print("[done] seeded 3 example encounters for avery-kim / riley-thompson")


if __name__ == "__main__":
    seed()
